os: osx
osx_image: xcode9.4

cache:
  - cocoapods
  - directories:
    - $HOME/.pub-cache
    - ios/vendor/bundle

install:
  - git clone -b beta https://github.com/flutter/flutter.git
  - export PATH=`pwd`/flutter/bin:$PATH
  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - flutter doctor -v
  - cd ios; bundle install --deployment

jobs:  
  include:
    - stage: "sync_code_signing"
      name: "sync_code_signing"
      script:
        - cd io
        - bundle exec fastlane sync_code_signing
