# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run Build"
  lane :build do
    puts 'Increment build number...'
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    puts 'Retrieving signing certificates and profiles...'
    sync_code_signing(
      git_url: ENV['PUBLISHING_MATCH_CERTIFICATE_REPO'],
      type: "appstore", 
      readonly: true
    )
    puts 'Certificates and profiles installed'
    disable_automatic_code_signing
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    # upload_to_testflight
  end
end
