# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Sync code sign"
  lane :retrieving_sign_development do
    puts 'Retrieving signing certificates and profiles...'
    sync_code_signing(
      app_identifier: "net.granoeste.example.helloflutter",
      type: "development", 
      readonly: true
    )
    sh("security find-identity -v -p codesigning")
  end

  lane :retrieving_sign_appstore do
    puts 'Retrieving signing certificates and profiles...'
    sync_code_signing(
      app_identifier: "net.granoeste.example.helloflutter",
      type: "appstore", 
      readonly: true
    )
    sh("security find-identity -v -p codesigning")
  end

  lane :retrieving_sign_adhoc do
    puts 'Retrieving signing certificates and profiles...'
    sync_code_signing(
      app_identifier: "net.granoeste.example.helloflutter",
      type: "adhoc", 
      readonly: true
    )
    sh("security find-identity -v -p codesigning")
  end

  desc "Run Build"
  lane :build do
    puts 'Certificates and profiles installed'
    disable_automatic_code_signing
    retrieving_sign_appstore
    puts 'Increment build number...'
    increment_build_number(xcodeproj: "Runner.xcodeproj")
    puts 'Build App...'
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
  end

  desc "Run Build and Testflight"
  lane :build_and_testflight do
    build
    puts 'Upload to Testflight...'
    upload_to_testflight
  end

  # Fastfile actions accept additional configuration, but
  # don't worry, fastlane will prompt you for required
  # info which you can add here later
  lane :beta do
    retrieving_sign_adhoc
    # build your iOS app
    puts 'Build App...'
    build_app(workspace: "Runner.xcworkspace", scheme: "Runner", export_method: "ad-hoc")

    # upload to Beta by Crashlytics
    crashlytics(
      api_token: "341962dabaa2652db56ede3bab74f9148b5093be",
      build_secret: "1a8c60811a7402f0f790d151d261fd37d5c850c466961af430256d97e2167ab9"
    )
  end

end
